name: Called workflow - Build

on: 
  workflow_dispatch:
  #[push, pull_request]
  workflow_call:
    inputs:
      configuration:
        default: 'Release'
        required: true
        type: string
jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore \src
    - name: Build
      run: dotnet build --configuration ${{ github.event.inputs.configuration }} --no-restore \src
    - name: Test
      run: dotnet test --no-build --verbosity normal \src
