name: LocalAction

on: 
  [workflow_dispatch]

jobs:
  hello_world_job1:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - id: hello-world
        uses: GHActionsTraining/.github/actions/myaction
        with:
          who-to-greet: 'Hello from GH ABCs'
      - run: echo random-number ${{ steps.hello-world.outputs.random-number }}
        shell: bash
